version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: socialnetwork
      POSTGRES_PASSWORD: pwd
    volumes:
      - pgdata:/var/lib/postgresql/data 
 
volumes:
  pgdata: